_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 32
buffer_capacity:
    value: 100000
env_name:
    value: ALE/Kaboom-v5
episodes:
    value: 500
epsilon_decay:
    value: 100000
epsilon_end:
    value: 0.1
epsilon_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
target_update_freq:
    value: 1000
